# Generated by Django 3.0.4 on 2020-04-14 01:58

from django.db import migrations, models
import django.db.models.deletion
import unicodex.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codepoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Totally optional, tbh.')),
                ('codepoint', models.CharField(blank=True, help_text='U+xxxx; tell me X, or I can work it out myself', max_length=10)),
                ('emojipedia_name', models.CharField(blank=True, help_text="If the name of this codepoint is strange on Emojipedia, add it here. Otherwise, I'll work it out myself.", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VendorVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicodex.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=unicodex.models.Design.design_path)),
                ('codepoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicodex.Codepoint')),
                ('vendorversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicodex.VendorVersion')),
            ],
            options={
                'unique_together': {('vendorversion', 'codepoint')},
            },
        ),
    ]
