#!/usr/bin/python
#
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 2.2.3 on 2019-07-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicodex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepoint',
            name='emojipedia_name',
            field=models.CharField(blank=True, help_text="If the name of this codepoint is strange on Emojipedia, add it here. Otherwise, I'll work it out myself.", max_length=20),
        ),
    ]
