# Generated by Django 2.2.3 on 2019-07-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicodex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepoint',
            name='emojipedia_name',
            field=models.CharField(blank=True, help_text="If the name of this codepoint is strange on Emojipedia, add it here. Otherwise, I'll work it out myself.", max_length=20),
        ),
    ]
