#!/usr/bin/python
#
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 2.2.4 on 2019-08-14 05:05

from django.db import migrations, models
import unicodex.models


class Migration(migrations.Migration):

    dependencies = [
        ('unicodex', '0002_codepoint_emojipedia_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepoint',
            name='description',
            field=models.TextField(blank=True, help_text='Totally optional, tbh.'),
        ),
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.FileField(upload_to=unicodex.models.Design.design_path),
        ),
    ]
