# Generated by Django 3.0.4 on 2020-08-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicodex', '0002_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepoint',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
