# Generated by Django 2.2.4 on 2019-08-14 05:05

from django.db import migrations, models
import unicodex.models


class Migration(migrations.Migration):

    dependencies = [
        ('unicodex', '0002_codepoint_emojipedia_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepoint',
            name='description',
            field=models.TextField(blank=True, help_text='Totally optional, tbh.'),
        ),
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.FileField(upload_to=unicodex.models.Design.design_path),
        ),
    ]
