# Generated by Django 2.2.4 on 2019-08-15 03:12


import django.apps

from django.db import migrations
from django.core.management import call_command

# https://docs.djangoproject.com/en/2.2/topics/migrations/#data-migrations

class Migration(migrations.Migration):

    dependencies = [
        ('unicodex', '0003_auto_20190814_0505'),
    ]

    operations = [
#        call_command('loaddata', 'vendor.yaml')
# This breaks: AttributeError: 'NoneType' object has no attribute 'state_forwards'
# Potentially a bug, probably user error

    ]
