# Generated by Django 2.2.7 on 2019-11-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicodex', '0004_vendor_fixutres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepoint',
            name='emojipedia_name',
            field=models.CharField(blank=True, help_text="If the name of this codepoint is strange on Emojipedia, add it here. Otherwise, I'll work it out myself.", max_length=50),
        ),
    ]
