steps:
  - id: Setup Script
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        source ./experimental/run_test.sh terraform
    
logsBucket: unicodex-ci-base-buildlogs
serviceAccount: projects/unicodex-ci-base/serviceAccounts/ci-serviceaccount@unicodex-ci-base.iam.gserviceaccount.com
