steps:
  - id: Setup Script
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        echo $BUILD_ID
        source ./experimental/run_test.sh terraform ${_PARENT_FOLDER}
    
logsBucket: unicodex-ci-base-buildlogs
serviceAccount: projects/unicodex-ci-base/serviceAccounts/ci-serviceaccount@unicodex-ci-base.iam.gserviceaccount.com

substitutions:
  _PARENT_FOLDER: "440127642793"

timeout: "1500s"