steps:
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_CI_PROJECT}/${_SERVICE}', '.']

  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_CI_PROJECT}/${_SERVICE}'] # latest potentially race condition
    

  - id: 'debug digest'
    name: "google/cloud-sdk"
    entrypoint: /bin/bash
    args: 
      - "-c"
      - |
        echo "script"
        echo source ./terraform/etc/get_image_digest.sh $_CI_PROJECT $_SERVICE
        source ./terraform/etc/get_image_digest.sh $_CI_PROJECT $_SERVICE

        echo ""
        echo gcloud container images list --filter $_SERVICE --project $_CI_PROJECT
        gcloud container images list --filter $_SERVICE --project $_CI_PROJECT

        echo ""
        echo gcloud container images list-tags gcr.io/$_CI_PROJECT/$_SERVICE --project $_CI_PROJECT
        gcloud container images list-tags gcr.io/$_CI_PROJECT/$_SERVICE --project $_CI_PROJECT

        echo ""
        echo gcloud container images describe gcr.io/${_CI_PROJECT}/${_SERVICE} --project $_CI_PROJECT
        gcloud container images describe gcr.io/${_CI_PROJECT}/${_SERVICE} --project $_CI_PROJECT

        echo ""
        echo gcloud container images describe gcr.io/${_CI_PROJECT}/${_SERVICE}:latest --project $_CI_PROJECT
        gcloud container images describe gcr.io/${_CI_PROJECT}/${_SERVICE}:latest --project $_CI_PROJECT

        echo ""
        echo "script again"
        source ./terraform/etc/get_image_digest.sh $_CI_PROJECT $_SERVICE


substitutions:
  _SERVICE: unicodex

logsBucket: ${PROJECT_ID}-buildlogs
serviceAccount: projects/$PROJECT_ID/serviceAccounts/ci-serviceaccount@unicodex-ci-base.iam.gserviceaccount.com