# Designed to be run in the CI project, which in this case will be *the* project.
steps:
  - id: "build"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE}", "."]

  - id: "push"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE}"]

  - id: "tf"
    name: "hashicorp/terraform:${_TF_VERSION}"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd terraform
        terraform init
        terraform refresh
        terraform apply -auto-approve \
          -var project=${PROJECT_ID} \
          -var instance_name=${_INSTANCE_NAME} \
          -var region=${_REGION} \
          -var service=${_SERVICE}

  - id: "migrate"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/${PROJECT_ID}/${_SERVICE}",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e",
        "PROJECT_ID=${PROJECT_ID}",
        "--",
        "sh",
        ".cloudbuild/django_migrate.sh",
      ]

  - id: "system test"
    name: $_PYTHON_VERSION
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        python -m pip install -r .util/requirements.txt
        .util/helper check-deploy $PROJECT_ID

  - id: "tf destroy"
    name: "hashicorp/terraform:${_TF_VERSION}"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd terraform
        terraform destroy -auto-approve -var project=${PROJECT_ID} 
        
substitutions:
  _SERVICE: unicodex
  _TF_VERSION: 0.15.4
  _PYTHON_VERSION: python:3.9-slim
  _REGION: us-central1
  _INSTANCE_NAME: psql

logsBucket: unicodex-ci-base-buildlogs
#serviceAccount: projects/unicodex-ci-base/serviceAccounts/ci-serviceaccount@unicodex-ci-base.iam.gserviceaccount.com

options:
  dynamic_substitutions: true

timeout: "1500s"