steps:
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_CI_PROJECT}/${_SERVICE}', '.']

  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_CI_PROJECT}/${_SERVICE}']
    

  - id: 'debug digest'
    name: "google/cloud-sdk"
    entrypoint: /bin/bash
    args: 
      - "-c"
      - |
        source ./terraform/etc/get_image_digest.sh $_CI_PROJECT $_SERVICE

  - id: 'tf init'
    name: 'hashicorp/terraform:${_TF_VERSION}'
    entrypoint: 'sh'
    args: 
    - '-c'
    - | 
      cd terraform
      terraform init

  - id: 'debug digest again'
    name: "google/cloud-sdk"
    entrypoint: /bin/bash
    args: 
      - "-c"
      - |
        source ./terraform/etc/get_image_digest.sh $_CI_PROJECT $_SERVICE

  - id: 'tf plan'
    name: 'hashicorp/terraform:${_TF_VERSION}'
    entrypoint: 'sh'
    args: 
    - '-c'
    - | 
      cd terraform
      terraform plan -var project=${_CI_PROJECT}

  - id: 'tf apply'
    name: 'hashicorp/terraform:${_TF_VERSION}'
    entrypoint: 'sh'
    args: 
    - '-c'
    - | 
      cd terraform
      terraform apply -auto-approve -var project=${_CI_PROJECT}
  
  - id: 'migrate'
    name: 'gcr.io/google-appengine/exec-wrapper'
    args: ['-i', 'gcr.io/${_CI_PROJECT}/${_SERVICE}',
            '-s', '${_CI_PROJECT}:${_REGION}:${_INSTANCE_NAME}',
            '-e', 'PROJECT_ID=${_CI_PROJECT}',
            '--', 'sh', '.cloudbuild/django_migrate.sh']

  - id: 'system test'
    name: $_PYTHON_VERSION
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        python -m pip install -r .util/requirements.txt
        .util/helper check-deploy $_CI_PROJECT

#  - id: 'tf destroy'
#    name: 'hashicorp/terraform:${_TF_VERSION}'
#    entrypoint: 'sh'
#    args: 
#    - '-c'
#    - | 
#      cd terraform
#      terraform destroy -auto-approve -var project=${_CI_PROJECT}

substitutions:
  _SERVICE: unicodex
  _TF_VERSION: 0.15.4
  _PYTHON_VERSION: python:3.9-slim
  _REGION: us-central1
  _INSTANCE_NAME: postgres

logsBucket: ${PROJECT_ID}-ci-logs # default
serviceAccount: projects/$PROJECT_ID/serviceAccounts/ci-service-account@glasnt-auto-1300.iam.gserviceaccount.com